{"ID": "8cd0b6a2-4488-4473-a95e-0c4752f29122", "effective_cve": "CVE-2020-8492", "image": {"exact": "docker.io/centos@sha256:3688aa867eb84332460e172b9250c9c198fdfd8d987605fd53f246f498c60bcf"}, "label": "TP", "package": {"name": "python", "version": "2.6.6-66.el6_8"}, "timestamp": "2022-09-15T18:57:13-04:00", "user": "wagoodman", "vulnerability_id": "CVE-2020-8492"}