{"ID": "758baa4b-5004-4fd7-b4c0-e1d6f6980714", "effective_cve": "CVE-2021-3737", "image": {"exact": "docker.io/anchore/test_images@sha256:0825acea611c7c5cc792bc7cc20de44d7413fd287dc5afc4aab9c1891d037b4f"}, "label": "TP", "package": {"name": "python3", "version": "3.8.10-r0"}, "timestamp": "2023-02-13T17:39:13+00:00", "tool": "grype@v0.56.0-30-g17e11ac", "user": "westonsteimel", "vulnerability_id": "CVE-2021-3737"}