{"ID": "546d8a9e-2777-4cfb-9eba-8055bb28db3f", "effective_cve": "CVE-2019-9947", "image": {"exact": "docker.io/ubuntu@sha256:881afbae521c910f764f7187dbfbca3cc10c26f8bafa458c76dda009a901c29d"}, "label": "TP", "package": {"name": "python3.4", "version": "3.4.3-1ubuntu1~14.04.7"}, "timestamp": "2023-06-29T18:35:20.181956", "tool": "grype@v0.63.0", "user": "westonsteimel", "vulnerability_id": "CVE-2019-9947"}