{"ID": "666ed7fb-a3b3-443e-84fa-b1a7d7cc118e", "effective_cve": "CVE-2018-20406", "image": {"exact": "docker.io/ubuntu@sha256:881afbae521c910f764f7187dbfbca3cc10c26f8bafa458c76dda009a901c29d"}, "label": "TP", "package": {"name": "python3.4", "version": "3.4.3-1ubuntu1~14.04.7"}, "timestamp": "2023-06-29T18:35:06.005590", "tool": "grype@v0.63.0", "user": "westonsteimel", "vulnerability_id": "CVE-2018-20406"}