{"ID": "9dbb07b7-81c9-4767-9139-1f8d9c1f10d9", "effective_cve": "CVE-2019-20907", "image": {"exact": "docker.io/ubuntu@sha256:881afbae521c910f764f7187dbfbca3cc10c26f8bafa458c76dda009a901c29d"}, "label": "TP", "package": {"name": "libpython3.4-stdlib", "version": "3.4.3-1ubuntu1~14.04.7"}, "timestamp": "2024-05-16T17:10:38.527977+00:00", "tool": "grype@v0.77.4", "user": "wagoodman", "vulnerability_id": "CVE-2019-20907"}