{"ID": "cf5b2798-f159-41de-8310-4af0f429801d", "effective_cve": "CVE-2017-20052", "image": {"exact": "docker.io/ubuntu@sha256:881afbae521c910f764f7187dbfbca3cc10c26f8bafa458c76dda009a901c29d"}, "label": "TP", "package": {"name": "libpython3.4-stdlib", "version": "3.4.3-1ubuntu1~14.04.7"}, "timestamp": "2024-05-16T17:10:35.542644+00:00", "tool": "grype@v0.77.4", "user": "wagoodman", "vulnerability_id": "CVE-2017-20052"}