{"ID": "b77d5b2e-a40d-4023-a1a2-fa3907b67b3f", "effective_cve": "CVE-2021-35937", "image": {"exact": "docker.io/rockylinux@sha256:72afc2e1a20c9ddf56a81c51148ebcbe927c0a879849efe813bee77d69df1dd8"}, "label": "FP", "note": "The package actually present is the RPM \"python3-rpm\", against which this CVE should actually be reported. See grype#1373.", "package": {"name": "rpm", "version": "4.14.3"}, "timestamp": "2023-08-02T23:49:35.533446", "tool": "grype@v0.65.0", "user": "willmurphy", "vulnerability_id": "CVE-2021-35937"}