{"ID": "ed1f30b3-8ece-4e65-bd3b-d4a0c87fa8ee", "effective_cve": "CVE-2017-1000158", "image": {"exact": "docker.io/anchore/test_images@sha256:b3534fc2e37943136d5b54e3a58b55d4ccd4363d926cf7aa5bf55a524cf8275b"}, "label": "FP", "package": {"name": "python-checks", "version": "3.4.1.8066"}, "timestamp": "2022-09-14T17:16:21+01:00", "user": "westonsteimel", "vulnerability_id": "CVE-2017-1000158"}