{"ID": "6ae410b5-a058-4fc2-92ab-49b6f73f24f0", "effective_cve": "CVE-2020-14830", "image": {"exact": "docker.io/anchore/test_images@sha256:f56164678054e5eb59ab838367373a49df723b324617b1ba6de775749d7f91d4"}, "label": "FP", "package": {"name": "mysql", "version": "2.18.1"}, "timestamp": "2022-09-14T17:48:46+01:00", "user": "westonsteimel", "vulnerability_id": "CVE-2020-14830"}