{"ID": "51fad23e-350c-4db4-a9e8-0918aedba370", "effective_cve": "CVE-2021-28861", "image": {"exact": "docker.io/almalinux@sha256:cd49d7250ed7bb194d502d8a3e50bd775055ca275d1d9c2785aea72b890afe6a"}, "label": "??", "package": {"name": "python3-libs", "version": "3.6.8-41.el8.alma"}, "timestamp": "2022-11-01T22:52:15+00:00", "tool": "grype@v0.51.0", "user": "westonsteimel", "vulnerability_id": "CVE-2021-28861"}