{"ID": "7a741501-245c-42db-afb4-6b567a77b33a", "effective_cve": "CVE-2018-25032", "image": {"exact": "docker.io/gitlab/gitlab-ce@sha256:04d4219d5dfb3acccc9997e50477c8d24b371387a95857e1ea8fc779e17a716c"}, "label": "TP", "package": {"name": "python", "version": "3.9.6"}, "timestamp": "2023-02-21T10:34:41+00:00", "tool": "grype@v0.56.0-7-ge3cda98", "user": "westonsteimel", "vulnerability_id": "CVE-2018-25032"}