{"ID": "ccfaabda-e329-4407-acb9-d01dce47205f", "effective_cve": "CVE-2021-4189", "image": {"exact": "docker.io/anchore/test_images@sha256:f8e72da9f67caf90714926e7b21f0da93ca1e528b37a97dffe71e2ec38872a8b"}, "label": "TP", "package": {"name": "python2.7-minimal", "version": "2.7.18-1~20.04.1"}, "timestamp": "2022-11-25T16:51:07+00:00", "tool": "grype@v0.53.1", "user": "westonsteimel", "vulnerability_id": "CVE-2021-4189"}