{"ID": "b8286761-5a93-4dd0-aee7-71355b1b3f1e", "effective_cve": "CVE-2020-29362", "image": {"exact": "docker.io/python@sha256:5e96e03a493a54904aa8be573fc0414431afb4f47ac58fbffd03b2a725005364"}, "label": "TP", "package": {"name": "libp11-kit0", "version": "0.23.15-2"}, "timestamp": "2022-09-29T22:07:00+01:00", "tool": "grype@34e08a0", "user": "westonsteimel", "vulnerability_id": "CVE-2020-29362"}